development: &development
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: clinica-dev

test: &test
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: clinica-test

production: &production
  adapter: mysql2
  host: localhost
  database: clinica-production
  username: your_production_database_login
  password: your_production_database_password
